name: infinite_pageview
description: "PageView but its infinite and can go left to the negatives!"
version: 0.0.1
homepage:

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: